[package]
name = "spacecraft"
version = "0.1.0"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]

[dependencies]
num = "0.1.36"
sdl2 = "0.27.0"
glium = "0.15.0"
glium_sdl2 = "0.13.0"
linalg = { path = "linalg" }
